FROM python

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/server.py .
COPY app/database.py .
COPY app/models.py .
COPY app/config.py .

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]